package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1



/**
 * Countrytable generated by hbm2java
 */
public class Countrytable  implements java.io.Serializable {


     private int logid;
     private Users users;
     private String countryname;

    public Countrytable() {
    }

    public Countrytable(int logid, Users users, String countryname) {
       this.logid = logid;
       this.users = users;
       this.countryname = countryname;
    }
   
    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCountryname() {
        return this.countryname;
    }
    
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }




}


