package db;
// Generated May 11, 2017 9:09:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Countrytable generated by hbm2java
 */
public class Countrytable  implements java.io.Serializable {


     private Integer logid;
     private String countryname;
     private Set userses = new HashSet(0);

    public Countrytable() {
    }

	
    public Countrytable(String countryname) {
        this.countryname = countryname;
    }
    public Countrytable(String countryname, Set userses) {
       this.countryname = countryname;
       this.userses = userses;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public String getCountryname() {
        return this.countryname;
    }
    
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


