package db;
// Generated May 7, 2017 8:49:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private Integer idgender;
     private String genderValue;
     private Set userses = new HashSet(0);

    public Gender() {
    }

    public Gender(String genderValue, Set userses) {
       this.genderValue = genderValue;
       this.userses = userses;
    }
   
    public Integer getIdgender() {
        return this.idgender;
    }
    
    public void setIdgender(Integer idgender) {
        this.idgender = idgender;
    }
    public String getGenderValue() {
        return this.genderValue;
    }
    
    public void setGenderValue(String genderValue) {
        this.genderValue = genderValue;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


