package db;
// Generated May 7, 2017 8:49:33 PM by Hibernate Tools 4.3.1



/**
 * Numberoflikes generated by hbm2java
 */
public class Numberoflikes  implements java.io.Serializable {


     private Integer numberoflikesLogid;
     private Post post;
     private Users users;
     private String remarks;

    public Numberoflikes() {
    }

	
    public Numberoflikes(Post post, Users users) {
        this.post = post;
        this.users = users;
    }
    public Numberoflikes(Post post, Users users, String remarks) {
       this.post = post;
       this.users = users;
       this.remarks = remarks;
    }
   
    public Integer getNumberoflikesLogid() {
        return this.numberoflikesLogid;
    }
    
    public void setNumberoflikesLogid(Integer numberoflikesLogid) {
        this.numberoflikesLogid = numberoflikesLogid;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


