package db;
// Generated May 11, 2017 9:09:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posttable generated by hbm2java
 */
public class Posttable  implements java.io.Serializable {


     private Integer postid;
     private Users users;
     private String content;
     private Date postdatetime;
     private int isactive;
     private byte posttype;
     private String subject;
     private int idofuser;
     private Set numberoflikeses = new HashSet(0);
     private Set usersandposts = new HashSet(0);
     private Set postkeywordses = new HashSet(0);

    public Posttable() {
    }

	
    public Posttable(Users users, String content, Date postdatetime, int isactive, byte posttype, String subject, int idofuser) {
        this.users = users;
        this.content = content;
        this.postdatetime = postdatetime;
        this.isactive = isactive;
        this.posttype = posttype;
        this.subject = subject;
        this.idofuser = idofuser;
    }
    public Posttable(Users users, String content, Date postdatetime, int isactive, byte posttype, String subject, int idofuser, Set numberoflikeses, Set usersandposts, Set postkeywordses) {
       this.users = users;
       this.content = content;
       this.postdatetime = postdatetime;
       this.isactive = isactive;
       this.posttype = posttype;
       this.subject = subject;
       this.idofuser = idofuser;
       this.numberoflikeses = numberoflikeses;
       this.usersandposts = usersandposts;
       this.postkeywordses = postkeywordses;
    }
   
    public Integer getPostid() {
        return this.postid;
    }
    
    public void setPostid(Integer postid) {
        this.postid = postid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getPostdatetime() {
        return this.postdatetime;
    }
    
    public void setPostdatetime(Date postdatetime) {
        this.postdatetime = postdatetime;
    }
    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
    public byte getPosttype() {
        return this.posttype;
    }
    
    public void setPosttype(byte posttype) {
        this.posttype = posttype;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public int getIdofuser() {
        return this.idofuser;
    }
    
    public void setIdofuser(int idofuser) {
        this.idofuser = idofuser;
    }
    public Set getNumberoflikeses() {
        return this.numberoflikeses;
    }
    
    public void setNumberoflikeses(Set numberoflikeses) {
        this.numberoflikeses = numberoflikeses;
    }
    public Set getUsersandposts() {
        return this.usersandposts;
    }
    
    public void setUsersandposts(Set usersandposts) {
        this.usersandposts = usersandposts;
    }
    public Set getPostkeywordses() {
        return this.postkeywordses;
    }
    
    public void setPostkeywordses(Set postkeywordses) {
        this.postkeywordses = postkeywordses;
    }




}


