package db;
// Generated May 11, 2017 9:09:59 PM by Hibernate Tools 3.6.0



/**
 * Postkeywords generated by hbm2java
 */
public class Postkeywords  implements java.io.Serializable {


     private Integer logid;
     private Posttable posttable;
     private String postkeywords;

    public Postkeywords() {
    }

    public Postkeywords(Posttable posttable, String postkeywords) {
       this.posttable = posttable;
       this.postkeywords = postkeywords;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public Posttable getPosttable() {
        return this.posttable;
    }
    
    public void setPosttable(Posttable posttable) {
        this.posttable = posttable;
    }
    public String getPostkeywords() {
        return this.postkeywords;
    }
    
    public void setPostkeywords(String postkeywords) {
        this.postkeywords = postkeywords;
    }




}


