package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private int postid;
     private String content;
     private Date postdatetime;
     private int isactive;
     private byte posttype;
     private Set numberoflikeses = new HashSet(0);
     private Set usersandposts = new HashSet(0);
     private Set postkeywordses = new HashSet(0);

    public Post() {
    }

	
    public Post(int postid, String content, Date postdatetime, int isactive, byte posttype) {
        this.postid = postid;
        this.content = content;
        this.postdatetime = postdatetime;
        this.isactive = isactive;
        this.posttype = posttype;
    }
    public Post(int postid, String content, Date postdatetime, int isactive, byte posttype, Set numberoflikeses, Set usersandposts, Set postkeywordses) {
       this.postid = postid;
       this.content = content;
       this.postdatetime = postdatetime;
       this.isactive = isactive;
       this.posttype = posttype;
       this.numberoflikeses = numberoflikeses;
       this.usersandposts = usersandposts;
       this.postkeywordses = postkeywordses;
    }
   
    public int getPostid() {
        return this.postid;
    }
    
    public void setPostid(int postid) {
        this.postid = postid;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getPostdatetime() {
        return this.postdatetime;
    }
    
    public void setPostdatetime(Date postdatetime) {
        this.postdatetime = postdatetime;
    }
    public int getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(int isactive) {
        this.isactive = isactive;
    }
    public byte getPosttype() {
        return this.posttype;
    }
    
    public void setPosttype(byte posttype) {
        this.posttype = posttype;
    }
    public Set getNumberoflikeses() {
        return this.numberoflikeses;
    }
    
    public void setNumberoflikeses(Set numberoflikeses) {
        this.numberoflikeses = numberoflikeses;
    }
    public Set getUsersandposts() {
        return this.usersandposts;
    }
    
    public void setUsersandposts(Set usersandposts) {
        this.usersandposts = usersandposts;
    }
    public Set getPostkeywordses() {
        return this.postkeywordses;
    }
    
    public void setPostkeywordses(Set postkeywordses) {
        this.postkeywordses = postkeywordses;
    }




}


