package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1



/**
 * Postkeywords generated by hbm2java
 */
public class Postkeywords  implements java.io.Serializable {


     private Integer logid;
     private Post post;
     private String postkeywords;

    public Postkeywords() {
    }

    public Postkeywords(Post post, String postkeywords) {
       this.post = post;
       this.postkeywords = postkeywords;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public String getPostkeywords() {
        return this.postkeywords;
    }
    
    public void setPostkeywords(String postkeywords) {
        this.postkeywords = postkeywords;
    }




}


