package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int roleid;
     private String rolediscription;
     private Set userroles = new HashSet(0);

    public Role() {
    }

	
    public Role(int roleid, String rolediscription) {
        this.roleid = roleid;
        this.rolediscription = rolediscription;
    }
    public Role(int roleid, String rolediscription, Set userroles) {
       this.roleid = roleid;
       this.rolediscription = rolediscription;
       this.userroles = userroles;
    }
   
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }
    public String getRolediscription() {
        return this.rolediscription;
    }
    
    public void setRolediscription(String rolediscription) {
        this.rolediscription = rolediscription;
    }
    public Set getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Set userroles) {
        this.userroles = userroles;
    }




}


