package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idusers;
     private String username;
     private Date birthday;
     private String gender;
     private String address;
     private String email;
     private byte[] photo;
     private Byte state;
     private Integer refid;
     private String password;
     private int score;
     private Integer counrtyid;
     private Set userroles = new HashSet(0);
     private Set countrytables = new HashSet(0);
     private Set usersandposts = new HashSet(0);
     private Set numberoflikeses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, Date birthday, String gender, String address, String email, int score) {
        this.username = username;
        this.birthday = birthday;
        this.gender = gender;
        this.address = address;
        this.email = email;
        this.score = score;
    }
    public Users(String username, Date birthday, String gender, String address, String email, byte[] photo, Byte state, Integer refid, String password, int score, Integer counrtyid, Set userroles, Set countrytables, Set usersandposts, Set numberoflikeses) {
       this.username = username;
       this.birthday = birthday;
       this.gender = gender;
       this.address = address;
       this.email = email;
       this.photo = photo;
       this.state = state;
       this.refid = refid;
       this.password = password;
       this.score = score;
       this.counrtyid = counrtyid;
       this.userroles = userroles;
       this.countrytables = countrytables;
       this.usersandposts = usersandposts;
       this.numberoflikeses = numberoflikeses;
    }
   
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }
    public Integer getRefid() {
        return this.refid;
    }
    
    public void setRefid(Integer refid) {
        this.refid = refid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    public Integer getCounrtyid() {
        return this.counrtyid;
    }
    
    public void setCounrtyid(Integer counrtyid) {
        this.counrtyid = counrtyid;
    }
    public Set getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Set userroles) {
        this.userroles = userroles;
    }
    public Set getCountrytables() {
        return this.countrytables;
    }
    
    public void setCountrytables(Set countrytables) {
        this.countrytables = countrytables;
    }
    public Set getUsersandposts() {
        return this.usersandposts;
    }
    
    public void setUsersandposts(Set usersandposts) {
        this.usersandposts = usersandposts;
    }
    public Set getNumberoflikeses() {
        return this.numberoflikeses;
    }
    
    public void setNumberoflikeses(Set numberoflikeses) {
        this.numberoflikeses = numberoflikeses;
    }




}


