package db;
// Generated May 11, 2017 9:09:59 PM by Hibernate Tools 3.6.0



/**
 * Usersandpost generated by hbm2java
 */
public class Usersandpost  implements java.io.Serializable {


     private int userspostLogid;
     private Posttable posttable;
     private Users users;
     private String comment;
     private Integer isactive;

    public Usersandpost() {
    }

	
    public Usersandpost(int userspostLogid, Posttable posttable, Users users, String comment) {
        this.userspostLogid = userspostLogid;
        this.posttable = posttable;
        this.users = users;
        this.comment = comment;
    }
    public Usersandpost(int userspostLogid, Posttable posttable, Users users, String comment, Integer isactive) {
       this.userspostLogid = userspostLogid;
       this.posttable = posttable;
       this.users = users;
       this.comment = comment;
       this.isactive = isactive;
    }
   
    public int getUserspostLogid() {
        return this.userspostLogid;
    }
    
    public void setUserspostLogid(int userspostLogid) {
        this.userspostLogid = userspostLogid;
    }
    public Posttable getPosttable() {
        return this.posttable;
    }
    
    public void setPosttable(Posttable posttable) {
        this.posttable = posttable;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }




}


