package db;
// Generated May 11, 2017 9:09:59 PM by Hibernate Tools 3.6.0



/**
 * Userrole generated by hbm2java
 */
public class Userrole  implements java.io.Serializable {


     private Integer logid;
     private Users users;
     private Role role;

    public Userrole() {
    }

    public Userrole(Users users, Role role) {
       this.users = users;
       this.role = role;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


