package db;
// Generated Apr 28, 2017 2:52:06 PM by Hibernate Tools 4.3.1



/**
 * Usersandpost generated by hbm2java
 */
public class Usersandpost  implements java.io.Serializable {


     private int userspostLogid;
     private Post post;
     private Users users;
     private String comment;
     private Integer isactive;

    public Usersandpost() {
    }

	
    public Usersandpost(int userspostLogid, Post post, Users users, String comment) {
        this.userspostLogid = userspostLogid;
        this.post = post;
        this.users = users;
        this.comment = comment;
    }
    public Usersandpost(int userspostLogid, Post post, Users users, String comment, Integer isactive) {
       this.userspostLogid = userspostLogid;
       this.post = post;
       this.users = users;
       this.comment = comment;
       this.isactive = isactive;
    }
   
    public int getUserspostLogid() {
        return this.userspostLogid;
    }
    
    public void setUserspostLogid(int userspostLogid) {
        this.userspostLogid = userspostLogid;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }




}


